# 日志级别
log_level = "trace"

# --- XDP 配置 ---
# 你的 XDP 程序将绑定到沙箱中的 veth_guest 接口
xdp_if_name = "eth3"

# 替换成你上一步获取到的 veth_guest 的 MAC 地址
xdp_mac = "a0:80:69:b8:94:67" 

# veth_guest 的 IP 地址
xdp_ip = "192.168.2.8"

# 允许以下 src IP 连接到 XDP listener。
xdp_acceptable_ips = []

xdp_skb_mod = true

# --- 网络路由配置 ---
# 沙箱的网关，即主机侧 veth_host 的 IP
gateway_ip = "192.168.2.1"

# --- 应用程序逻辑配置 ---
# 你需要连接的外部 WebSocket 服务器地址
ws_uri = "wss://ws.okx.com/ws/" # 这是一个公开的测试 WebSocket Echo 服务

# CSV 输出路径
output_csv_path = "output.csv"
